name: publish snapshot

on:
  push:
    branches:
      - 'master'
      - 'snapshot/*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:

  upload:
    name: Upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install curl
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt install -y libcurl4-gnutls-dev
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Check
        run: ./gradlew check
      - name: Publish Linux to Maven Local
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: ./gradlew publishLinuxX64PublicationToMavenLocal
      - name: Publish MacOS to Maven Local
        if: matrix.os == 'macOS-latest'
        shell: bash
        run: ./gradlew publishToMavenLocal
      - name: Copy artifact files
        run: |
          mkdir -p maven-local/snapshot
          cp -r ~/.m2/repository/* maven-local/snapshot
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snapshot
          path: |
            maven-local
            !maven-local/**/maven-metadata-local.xml
