name: Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'
  push:
    branches:
      - 'master'
      - '!snapshot/*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'

jobs:

  upload:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    steps:

      # 1 - checkout repositories
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install curl
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt install -y libcurl4-gnutls-dev

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 4 - tests
      - name: Check with integration
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build -PintegrationTests=include
      - name: Check without integration
        if: matrix.os == 'macOS-latest'
        run: ./gradlew build -x jvmTest

      # Uncomment the lines below to store test results for debugging failed tests (useful for iOS)
      # - name: Store test results
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test results
      #     path: build/reports
      #     retention-days: 1
